language: python
python:
  - "3.6"
cache:
  apt: true
  timeout: 1000
  directories:
    - $HOME/.cache/pip
    - $HOME/miniconda_cache
install:
  - sudo apt-get update

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
  - bash $HOME/miniconda.sh -b -p $HOME/miniconda

  # copy cached bz2 files to $HOME/miniconda/pkgs
  - cp -v $HOME/miniconda_cache/*.bz2 $HOME/miniconda/pkgs

  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda env create -q -n skorch-env -f environment.yml
  - source activate skorch-env
  - conda install --file=requirements-dev.txt
  - python setup.py install
  - conda install -c pytorch 'pytorch-cpu>=0.3.0'

  # copy bz2 files to cache
  - cp -v $HOME/miniconda/pkgs/*.bz2 $HOME/miniconda_cache/*.bz2
script:
  - pytest
